openapi: 3.0.0
info:
  title: "Manual Test Site API"
  version: 0.0.1
  description: |
    This specification outlines the underlying api for use in the manual testing site (name is a work in progress).
    The goal of this site is to allow for the easy creation, organization and running of manual tests whilst also providing an image based interface to view the status of a project or story at a glance.
servers:
  - url: http://localhost:4941/api/v1
    description: "Your development server"
tags:
  - name: projects
  - name: stories
  - name: tests
paths:
  /projects:
    get:
      tags:
        - projects
      summary: |
        Get a list of all projects on the server
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectList"
    post:
      tags:
        - projects
      summary: |
        Create a new project
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProject"
      responses:
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                properties:
                  projectId:
                    $ref: "#/components/schemas/Project/properties/projectId"
  /project/{project_id}/stories:
    parameters:
      - name: project_id
        description: "The id of the project"
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/Project/properties/projectId"
    get:
      tags:
        - stories
      summary: |
        Get a list of all stories for the given project.
        A story is simply a grouping of related manual tests
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StoryList"
    post:
      tags:
        - stories
      summary: |
        Create a new story for a project
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateStory"
      responses:
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                properties:
                  storyId:
                    $ref: "#/components/schemas/Story/properties/storyId"
  /project/{project_id}/stories/{story_id}/tests:
    parameters:
      - name: project_id
        description: "The id of the project"
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/Project/properties/projectId"
      - name: story_id
        description: "The id of the story"
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/Story/properties/storyId"
    get:
      tags:
        - tests
      summary: |
        Get a list of all tests for the given story.
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestList"
    post:
      tags:
        - tests
      summary: |
        Create a new test for a story
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTest"
      responses:
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                properties:
                  storyId:
                    $ref: "#/components/schemas/Test/properties/testId"


components:
  schemas:
    Project:
      type: object
      allOf:
        - $ref: "#/components/schemas/CreateProject"
      properties:
        projectId:
          type: integer
          example: 1
        status:
          type: string
          enum:
            - PASSING
            - FAILING
            - ERROR
            - UNKNOWN
        numStories:
          type: integer
          example: 1
        numTests:
          type: integer
          example: 1
    ProjectList:
      type: array
      items: 
        $ref: "#/components/schemas/Project"
    CreateProject:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 128
          example: "My first project"
        description:
          type: string
          minLength: 0
          maxLength: 1024
          example: "Example project description"
    Story:
      type: object
      allOf:
        - $ref: "#/components/schemas/CreateStory"
      properties:
        storyId:
          type: integer
          example: 1
        status:
          type: string
          enum:
            - PASSING
            - FAILING
            - ERROR
            - UNKNOWN
        numTests:
          type: integer
          example: 1
    StoryList:
      type: array
      items:
        $ref: "#/components/schemas/Story"
    CreateStory:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 128
          example: "U1: My first story"
        description:
          type: string
          minLength: 0
          maxLength: 1024
          example: "Example story description"
    Test:
      type: object
      allOf:
        - $ref: "#/components/schemas/CreateStory"
      properties:
        testId:
          type: integer
          example: 1
        storyId:
          type: integer
          example: 1
        status:
          type: string
          enum:
            - PASSING
            - FAILING
            - ERROR
            - UNKNOWN
        numRuns:
          type: integer
          example: 1
    TestList:
      type: array
      items:
        $ref: "#/components/schemas/Test"
    CreateTest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 128
          example: "My first test"
        description:
          type: string
          minLength: 0
          maxLength: 1024
          example: "Example test description"
      

    
    
